name = "SBSTest"
defaultTargets = ["SBSTest"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.27.0"

[[require]]
name = "Dress"
path = "../Dress"

[[require]]
name = "subverso"
path = "../../forks/subverso"

[[require]]
name = "verso"
git = "https://github.com/e-vergo/verso.git"
rev = "main"

[[lean_lib]]
name = "SBSTest"

[[lean_exe]]
name = "generate-blueprint-verso"
root = "GenerateBlueprint"

[[lean_exe]]
name = "generate-paper-verso"
root = "GeneratePaper"
